package com.harold.my_stats.service

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.IBinder
import androidx.core.app.NotificationCompat
import androidx.core.content.ContextCompat
import com.harold.my_stats.BuildConfig
import com.harold.my_stats.R
import com.harold.my_stats.collector.DeviceSnapshotCollector
import com.harold.my_stats.db.AppSettingsEntity
import com.harold.my_stats.db.MyStatsDatabase
import com.harold.my_stats.db.ReportDao
import com.harold.my_stats.db.ReportEntity
import com.harold.my_stats.model.DebugReportPayload
import com.harold.my_stats.network.ReportUploader
import com.harold.my_stats.util.CompressedJsonStrings
import com.harold.my_stats.util.JsonUtils
import com.harold.my_stats.util.Prefs
import com.harold.my_stats.util.TimeUtils
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString

class CollectorService : Service() {
    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private lateinit var prefs: Prefs
    private lateinit var collector: DeviceSnapshotCollector
    private var lastUploadAttemptEpochMs = 0L

    override fun onCreate() {
        super.onCreate()
        prefs = Prefs(this)
        prefs.setCollectorRunning(true)
        collector = DeviceSnapshotCollector(this, prefs)
        lastUploadAttemptEpochMs = System.currentTimeMillis()
        startForegroundInternal()
        serviceScope.launch { runLoop() }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_FLUSH_NOW) {
            serviceScope.launch {
                flushPending(MyStatsDatabase.get().reportDao())
            }
        }
        return START_STICKY
    }

    override fun onDestroy() {
        prefs.setCollectorRunning(false)
        serviceScope.cancel()
        super.onDestroy()
    }

    override fun onBind(intent: Intent?): IBinder? = null

    private suspend fun runLoop() {
        val dao = MyStatsDatabase.get().reportDao()
        while (serviceScope.isActive) {
            val now = System.currentTimeMillis()
            prefs.setLastHeartbeatEpochMs(now)
            collectAndStore(dao, now)
            if (now - lastUploadAttemptEpochMs >= uploadIntervalMs()) {
                lastUploadAttemptEpochMs = now
                flushPending(dao)
            }
            delay(COLLECTION_INTERVAL_MS)
        }
    }

    private suspend fun collectAndStore(dao: ReportDao, now: Long) {
        val payload = runCatching {
            val result = collector.collect(now)
            val snapshotString = JsonUtils.encodeElement(result.snapshotJson)
            val batteryLevel = Regex("\"levelPct\":(-?\\d+)").find(snapshotString)?.groupValues?.getOrNull(1)?.toIntOrNull() ?: -1
            val imei = Regex("\"imei\":\"(.*?)\"").find(snapshotString)?.groupValues?.getOrNull(1) ?: ""
            DebugReportPayload(
                app_install_id = BuildConfig.APP_INSTALL_ID,
                device_id = BuildConfig.DEVICE_ID,
                battery = batteryLevel,
                imei = imei,
                category = "heartbeat.stats",
                description = "Periodic my stats snapshot.",
                severity = "info",
                stacktrace = result.crashStackSummary,
                extra_json = snapshotString,
                git_branch = BuildConfig.GIT_BRANCH,
                debug_notes = "Generated by persistent foreground collector service",
                created_at = TimeUtils.nowEndpointString()
            )
        }.getOrElse {
            DebugReportPayload(
                app_install_id = BuildConfig.APP_INSTALL_ID,
                device_id = BuildConfig.DEVICE_ID,
                battery = -1,
                imei = "",
                category = "collector.failure",
                description = "Collector loop failed before snapshot completed.",
                severity = "error",
                stacktrace = it.stackTraceToString(),
                extra_json = "{}",
                git_branch = BuildConfig.GIT_BRANCH,
                debug_notes = "Collector exception",
                created_at = TimeUtils.nowEndpointString()
            )
        }

        val json = JsonUtils.json.encodeToString(payload)
        dao.insert(ReportEntity(createdAtEpochMs = now, payloadJson = CompressedJsonStrings.compress(json)))
        dao.trimToMaxRows(MAX_LOCAL_REPORTS)
        prefs.incrementCollectedCount()
        notifyCollectionDataChanged()
    }

    private suspend fun flushPending(dao: ReportDao) {
        val endpointUrl = endpointUrlForUpload()
        dao.getPending(MAX_LOCAL_REPORTS).forEach { entity ->
            runCatching {
                val json = CompressedJsonStrings.decompress(entity.payloadJson)
                val payload = JsonUtils.json.decodeFromString<DebugReportPayload>(json)
                ReportUploader.upload(payload, endpointUrl)
                dao.deleteById(entity.localId)
                prefs.incrementSentEndpointCount()
                MyStatsDatabase.get().appSettingsDao().incrementSentEndpointCount()
                notifyCollectionDataChanged()
            }.onFailure {
                dao.markFailed(entity.localId, it.message)
                prefs.incrementFailedEndpointCount()
                MyStatsDatabase.get().appSettingsDao().incrementFailedEndpointCount()
                notifyCollectionDataChanged()
            }
        }
    }

    private suspend fun endpointUrlForUpload(): String {
        val settings = settingsForUpload()
        return settings.endpointUrl
    }

    private suspend fun uploadIntervalMs(): Long {
        val settings = settingsForUpload()
        return settings.uploadIntervalMs.coerceAtLeast(COLLECTION_INTERVAL_MS)
    }

    private suspend fun settingsForUpload(): AppSettingsEntity {
        val dao = MyStatsDatabase.get().appSettingsDao()
        val existing = dao.get()
        if (existing != null) return existing
        val defaults = AppSettingsEntity()
        dao.save(defaults)
        return defaults
    }

    private fun notifyCollectionDataChanged() {
        sendBroadcast(Intent(ACTION_COLLECTION_DATA_CHANGED).setPackage(packageName))
    }

    private fun startForegroundInternal() {
        val channelId = "my_stats_collector"
        val nm = getSystemService(NotificationManager::class.java)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(channelId, getString(R.string.channel_name), NotificationManager.IMPORTANCE_LOW).apply {
                description = getString(R.string.channel_description)
                setShowBadge(false)
            }
            nm.createNotificationChannel(channel)
        }
        val notification: Notification = NotificationCompat.Builder(this, channelId)
            .setSmallIcon(android.R.drawable.stat_notify_sync)
            .setContentTitle(getString(R.string.notification_title))
            .setContentText(getString(R.string.notification_text))
            .setOngoing(true)
            .build()
        startForeground(1001, notification)
    }

    companion object {
        private const val COLLECTION_INTERVAL_MS = 10_000L
        private const val ACTION_FLUSH_NOW = "com.harold.my_stats.action.FLUSH_NOW"
        const val ACTION_COLLECTION_DATA_CHANGED = "com.harold.my_stats.action.COLLECTION_DATA_CHANGED"
        private const val MAX_LOCAL_REPORTS = 8_640

        fun start(context: Context) {
            ContextCompat.startForegroundService(context, Intent(context, CollectorService::class.java))
        }

        fun flushNow(context: Context) {
            val intent = Intent(context, CollectorService::class.java).setAction(ACTION_FLUSH_NOW)
            ContextCompat.startForegroundService(context, intent)
        }

        fun stop(context: Context) {
            Prefs(context).setCollectorRunning(false)
            context.stopService(Intent(context, CollectorService::class.java))
        }
    }
}
